### ISSUE TITLE
Failed Pre-Requisite Check but Node.js and Topojson already installed Windows 7 

### ISSUE THREAD

**Issue by rnanclares** [sbenten/d3MapRenderer#10]
Hi there, i was testing the plugin but i couldn't get it to work. I've installed Node.js and Topojson. Tried to unistall the plugin, and re-install but still failing the prerequisite check. I've also tried the master version on github withe same results.

The QGIS log: 
2015-09-18T16:42:47 0   model 2.10.1-Pisa
2015-09-18T16:42:47 0   model 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
2015-09-18T16:42:47 0   topo Windows
2015-09-18T16:42:47 2   model Exception
            Traceback (most recent call last):
              File "C:/Users/User/.qgis2/python/plugins\d3MapRenderer\logic.py", line 100, in hasTopoJson
                found = self.topojson.helper.hasTopojson()
              File "C:/Users/User/.qgis2/python/plugins\d3MapRenderer\osHelp.py", line 139, in hasTopojson
                nodeFound = self.getNodeJsPath()
              File "C:/Users/User/.qgis2/python/plugins\d3MapRenderer\osHelp.py", line 235, in getNodeJsPath
                except self.reg.WindowsError as e:
            AttributeError: 'module' object has no attribute 'WindowsError'
Cheers!

**Comment by tomchadwin** [comment]
I still get this error with current master. I don't have the registry key mentioned in #11.

**Comment by sbenten** [comment]
Yes, it's causing some problems on various platforms, so I'm in the process
of adding in Calving Metcalfs' topojson.py.  Just a shame it doesn't work
out for the box within Qgis...

Thanks
