### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower

### ISSUE THREAD

**Issue by smitty1788** [sbenten/d3MapRenderer#33]
Error occurs when trying to run plugin after shapefile has been stylized both categorically or using graduated colors. Python log is below.

Python error: 

2016-11-11T12:53:55	1	Traceback (most recent call last):
			  File "C:/Users/smithr/.qgis2/python/plugins\d3MapRenderer\d3_Map.py", line 704, in run
			    self.setupUI()
			  File "C:/Users/smithr/.qgis2/python/plugins\d3MapRenderer\d3_Map.py", line 715, in setupUI
			    self.model.setup()
			  File "C:/Users/smithr/.qgis2/python/plugins\d3MapRenderer\logic.py", line 131, in setup
			    self.vectors.append(vector(self.iface, layer))
			  File "C:/Users/smithr/.qgis2/python/plugins\d3MapRenderer\logic.py", line 792, in __init__
			    self.hasLabel = self.hasLabels()
			  File "C:/Users/smithr/.qgis2/python/plugins\d3MapRenderer\logic.py", line 829, in hasLabels
			    enabled = self.layer.customProperty("labeling/enabled").lower() == "true"
			AttributeError: 'bool' object has no attribute 'lower'

**Comment by sbenten** [comment]
Already fixed on the master branch. Preparing a release of the updated v0.10 branch that is currently released. You can download the latest version of either archive to get you past the problem.
